title: Marcin Floryan
description: >
  Marcin Floryan: Working with psychological safety, technology and complexity 
  to understand and influence systems of work. http://pronoun.is/he; agile descaler @Spotify
tagline: Marcin's personal wesbite
locale: en_GB
lang: en_GB
author:
  name: Marcin Floryan
  twitter: mfloryan
  url: https://marcin.floryan.pl/
social:
  name: Marcin Floryan
  links:
    - https://twitter.com/mfloryan
    - https://www.facebook.com/mfloryan
    - https://www.linkedin.com/in/mfloryan/
    - https://github.com/mfloryan
    - https://keybase.io/mfloryan
 social_links:
    twitter: mfloryan
    github:  mfloryan
    facebook: mfloryan
    instagram: mf.se
    linkedin: mfloryan
    keybase: mfloryan
plugins:
  - jekyll-seo-tag