name: mf-site

services:
  serve:
    build: .
    image: mf-site-jekyll
    volumes:
      - ./site:/site
    ports:
      - 4000:4000
      - 35729:35729
    command: >
      bundle exec jekyll serve --livereload --livereload-min-delay 5 --trace --host 0.0.0.0
    environment:
      - JEKYLL_ENV=development

  build:
    image: mf-site-jekyll
    volumes:
      - ./site:/site
    command: >
      bundle exec jekyll build --verbose --destination marcin.floryan.pl/
    environment:
      - JEKYLL_ENV=production
