title: Marcin Floryan
description: >
  Marcin Floryan: Working with psychological safety, technology and complexity 
  to understand and influence systems of work. http://pronoun.is/he; agile descaler @Spotify
tagline: Marcin's personal wesbite
keywords:
  - Marcin Floryan
  - software development
  - Spotify
  - leadership
  - engineering
  - agile
author:
  name: Marcin Floryan
  twitter: mfloryan
  url: https://marcin.floryan.pl/

future: true
collections:
  events:
    output: true
    permalink: /events/:year/:slug
  posts:
    permalink: /blog/:year/:month/:slug

social:
  name: Marcin Floryan
  links:
    - https://twitter.com/mfloryan
    - https://www.facebook.com/mfloryan
    - https://www.linkedin.com/in/mfloryan/
    - https://github.com/mfloryan
    - https://keybase.io/mfloryan
    - https://mstdn.social/@mfloryan
social_links:
  twitter: mfloryan
  github: mfloryan
  facebook: mfloryan
  instagram: mf.se
  linkedin: mfloryan
  keybase: mfloryan
  mastodon: "@mfloryan@mstdn.social"

locale: en_GB
lang: en_GB
timezone: Europe/Stockholm
exclude: ['*.sh', '_tools/', 'README.md', '_sass']
plugins:
  - jekyll-seo-tag
  - jekyll-figure
  - jekyll-last-modified-at

jekyll-figure:
  paragraphs: false
